# set environment variables by copying and customizing http-client.env.json.dist to http-client.env.json

POST {{host}}/calculate

< tests/fixtures/camelcase-messy.php

###

POST {{host}}/calculate

< tests/fixtures/camelcase-clean.php

###
