services:
    database:
        image: 'postgres:15'
        ports:
            - '8432:5432'
        environment:
            POSTGRES_DB: 'symfony'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - ./data:/data

volumes:
    data:
