version: '3.1'

services:
    database:
        image: 'postgres:12.1'
        restart: 'always'
        ports:
            - '8432:5432'
        environment:
            POSTGRES_PASSWORD: 'password'
        volumes:
            - ./data:/data
